In [1]:
import torch
from torch.utils.data import Dataset, DataLoader

In [4]:
def causal_mask(size):
  mask = torch.triu(torch.ones(1, size, size), diagonal=1).type(torch.int)
  return mask == 0

res = causal_mask(3)
print(res)

NameError: name 'torch' is not defined

In [2]:
if torch.backends.mps.is_available():
  mps_device = torch.device("mps")
  x = torch.ones(1, device=mps_device)
  print (x)
else:
  print("MPS not found")

tensor([1.], device='mps:0')


In [5]:
class CustomDataset(Dataset):
  def __init__(self, data):
    self.data = data
    
  def __len__(self):
    return len(self.data)
  
  def __getitem__(self, index):
    return self.data[index]
  

data = list(range(100))
dataset = CustomDataset(data)

dataloader = DataLoader(dataset, batch_size=10, shuffle=True)

for batch in dataloader:
  print(batch)  

tensor([29, 83,  2, 54, 95, 30,  5, 34, 17, 93])
tensor([ 8, 33, 19, 46, 79, 35, 10, 59,  6, 31])
tensor([20, 84, 38, 44, 67, 66, 12, 37,  9, 45])
tensor([60,  3, 49, 52, 88, 63, 82, 65, 53, 94])
tensor([47, 27,  4, 74, 28, 26,  0, 96, 21, 13])
tensor([70, 78, 76, 16, 50, 89, 11, 18, 85, 81])
tensor([98, 97, 55, 91, 92, 32, 14, 87, 25, 48])
tensor([58, 68, 41, 42, 22, 15,  7, 99, 39, 36])
tensor([23, 57, 73,  1, 56, 71, 69, 72, 40, 62])
tensor([64, 43, 86, 80, 61, 77, 24, 90, 51, 75])


In [2]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)
print()

#Additional Info when using cuda
if device.type == 'cuda':
    print(torch.cuda.get_device_name(0))
    print('Memory Usage:')
    print('Allocated:', round(torch.cuda.memory_allocated(0)/1024**3,1), 'GB')
    print('Cached:   ', round(torch.cuda.memory_reserved(0)/1024**3,1), 'GB')

Using device: cuda

NVIDIA GeForce RTX 2060
Memory Usage:
Allocated: 0.0 GB
Cached:    0.0 GB


In [3]:
torch.cuda.is_available()

True

In [4]:
torch.zeros(1).cuda()

tensor([0.], device='cuda:0')